"""initial migration

Revision ID: 18e553ce163f
Revises: 
Create Date: 2025-04-23 18:58:05.777515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e553ce163f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_id'), 'session', ['id'], unique=False)
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doam', sa.Double(), nullable=True),
    sa.Column('nhietdo', sa.Double(), nullable=True),
    sa.Column('co2', sa.Double(), nullable=True),
    sa.Column('co', sa.Double(), nullable=True),
    sa.Column('nh3', sa.Double(), nullable=True),
    sa.Column('toluen', sa.Double(), nullable=True),
    sa.Column('c6h6', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_doam'), 'data', ['doam'], unique=False)
    op.create_index(op.f('ix_data_id'), 'data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_id'), table_name='data')
    op.drop_index(op.f('ix_data_doam'), table_name='data')
    op.drop_table('data')
    op.drop_index(op.f('ix_session_id'), table_name='session')
    op.drop_table('session')
    # ### end Alembic commands ###
